name: ultimate_salon_owner_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.20
  get: ^4.6.5
  skeletons: ^0.0.3
  image_picker: ^0.8.7+1
  syncfusion_flutter_calendar: ^21.1.37
  jiffy: ^5.0.0
  flutter_html: ^3.0.0-alpha.5
  connectivity_plus: ^3.0.3
  google_nav_bar: ^5.0.6
  syncfusion_flutter_charts: ^21.1.37
  flutter_otp_text_field: ^1.1.1
  webview_flutter: ^4.0.7
  country_code_picker: ^3.0.0
  url_launcher: ^6.1.10
  country_picker: ^2.0.20
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf