/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Ultimate Salon Full App Flutter V2
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2023-present initappz.
*/
import "package:get/get.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Add Packages": "Add Packages",
          "Choose From": "Choose From",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "Cancel": "Cancel",
          "Select Categories": "Select Categories",
          "Select Specialist": "Select Specialist",
          "Packages Name": "Packages Name",
          "Price": "Price",
          "Discount": "Discount",
          "Sell Price": "Sell Price",
          "Descriptions": "Descriptions",
          "Duration": "Duration",
          "Upload More Image": "Upload More Image",
          "ADD PACKAGES": "ADD PACKAGES",
          "UPDATE PACKAGES": "UPDATE PACKAGES",
          "Add Service": "Add Service",
          "Service Name": "Service Name",
          "Categories": "Categories",
          "Service Price": "Service Price",
          "Discount %": "Discount %",
          "Service Duration": "Service Duration",
          "Description": "Description",
          "Available": "Available",
          "Hide": "Hide",
          "Status": "Status",
          "SUBMIT": "SUBMIT",
          "UPDATE": "UPDATE",
          "Add Slots": "Add Slots",
          "Sunday": "Sunday",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "Open Time": "Open Time",
          "Close Time": "Close Time",
          "Are you sure": "Are you sure",
          "to delete this slot ?": "to delete this slot ?",
          "Delete": "Delete",
          "Add": "Add",
          "Save & Submit": "Save & Submit",
          "Add Stylist": "Add Stylist",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Add Timing": "Add Timing",
          "Save": "Save",
          "Update": "Update",
          "Daily": "Daily",
          "Monthly": "Monthly",
          "Yearly": "Yearly",
          "Analyze": "Analyze",
          "Appointment": "Appointment",
          "Products Order": "Products Order",
          "Earnings": "Earnings",
          "Total": "Total",
          "Average": "Average",
          "Day": "Day",
          "Bookings": "Bookings",
          "Months": "Months",
          "Orders": "Orders",
          "Total number of bookings": "Total number of bookings",
          "Total number of orders": "Total number of orders",
          "Appointments History": "Appointments History",
          "New": "New",
          "Old": "Old",
          "At Salon": "At Salon",
          "Appointments ID #": "Appointments ID #",
          "Services": "Services",
          "Packages": "Packages",
          "Grand Total :": "Grand Total :",
          "Appointment at :": "Appointment at :",
          "No New Appointment Found!": "No New Appointment Found!",
          "No Past Appointment Found!": "No Past Appointment Found!",
          "Calendar": "Calendar",
          "No Appointment Found!": "No Appointment Found!",
          "Message...": "Message...",
          "Select Cities": "Select Cities",
          "Cancle": "Cancle",
          "Submit": "Submit",
          "Contact Us": "Contact Us",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Create Products": "Create Products",
          "Update Products": "Update Products",
          "Select Subcategories": "Select Subcategories",
          "Sub Categories": "Sub Categories",
          "Products Name": "Products Name",
          "Products Price": "Products Price",
          "in Offers": "in Offers",
          "in Stock": "in Stock",
          "in Home": "in Home",
          "in Single": "in Single",
          "in Gram": "in Gram",
          "Gram Value": "Gram Value",
          "in KG": "in KG",
          "KG Value": "KG Value",
          "in Liter": "in Liter",
          "Liter Value": "Liter Value",
          "in PCs": "in PCs",
          "PCs Value": "PCs Value",
          "in ML": "in ML",
          "ML Value": "ML Value",
          "Expired Date": "Expired Date",
          "Connection Failed": "Connection Failed",
          "Could not connect to network": "Could not connect to network",
          "Please check and try again": "Please check and try again",
          "retry": "retry",
          "Verify your phone number": "Verify your phone number",
          "Gallary": "Gallary",
          "Upload Image": "Upload Image",
          "Update Images": "Update Images",
          "Order History": "Order History",
          "Order Id #": "Order Id #",
          "Order At : ": "Order At : ",
          "Grand Total : ": "Grand Total : ",
          "No New Orders Found!": "No New Orders Found!",
          "No Past Orders Found!": "No Past Orders Found!",
          "Messages": "Messages",
          "Select Individual Categories": "Select Individual Categories",
          "Brief Of Salon": "Brief Of Salon",
          "Enter Address..": "Enter Address..",
          "Select": "Select",
          "ZIP Code": "ZIP Code",
          "Latitude": "Latitude",
          "Longitude": "Longitude",
          "Have Popular ?": "Have Popular ?",
          "Have Shop ?": "Have Shop ?",
          "Have Home ?": "Have Home ?",
          "Opening Hour": "Opening Hour",
          "Edit": "Edit",
          "Languages": "Languages",
          "Welcome": "Welcome",
          "Login With Your Account": "Login With Your Account",
          "Email ID": "Email ID",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "LOG IN": "LOG IN",
          "Don't have an Account? Sign Up": "Don't have an Account? Sign Up",
          "Mobile Number": "Mobile Number",
          "Appointments No #": "Appointments No #",
          "Service At": "Service At",
          "Booking Date & Time": "Booking Date & Time",
          "Booking Date": "Booking Date",
          "Booking Time": "Booking Time",
          "Pricing": "Pricing",
          "Wallet Discount": "Wallet Discount",
          "Distance Cost": "Distance Cost",
          "Service Tax": "Service Tax",
          "Payment": "Payment",
          "Total Amount": "Total Amount",
          "Your Appoinments Status": "Your Appoinments Status",
          "Accept": "Accept",
          "Decline": "Decline",
          "Update Status": "Update Status",
          "Select Packages": "Select Packages",
          "and more": "and more",
          "Add New": "Add New",
          "to delete Slots ?": "to delete Slots ?",
          "Order No #": "Order No #",
          "Delivery Address": "Delivery Address",
          "Order Date": "Order Date",
          "Your Order Status": "Your Order Status",
          "Products": "Products",
          "Search for Salon, Services....": "Search for Salon, Services....",
          "Enter Salon Name": "Enter Salon Name",
          "Have Multiple Stylist ?": "Have Multiple Stylist ?",
          " Reviews) ": " Reviews) ",
          "Your Profile": "Your Profile",
          "Edit Profile": "Edit Profile",
          "Chats": "Chats",
          "Review": "Review",
          "Slots": "Slots",
          "Stylist": "Stylist",
          "History": "History",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "Help": "Help",
          "Privacy Policy": "Privacy Policy",
          "Terms & Conditions": "Terms & Conditions",
          "About us": "About us",
          "About": "About",
          "Logout": "Logout",
          "Served Category": "Served Category",
          "All Reviews": "All Reviews",
          "Select Salon Categories": "Select Salon Categories",
          "Select Services": "Select Services",
          "Select Shop Categories": "Select Shop Categories",
          "Select Shop Subcategories": "Select Shop Subcategories",
          "Send Register Request": "Send Register Request",
          "Next": "Next",
          "Previews": "Previews",
          "Select your type": "Select your type",
          "Salon": "Salon",
          "Individual": "Individual",
          "Email": "Email",
          "Verify": "Verify",
          "Verified": "Verified",
          "Search": "Search",
          "Start typing to search": "Start typing to search",
          "Code": "Code",
          "Phone": "Phone",
          "Salon Name": "Salon Name",
          "Confirm Password": "Confirm Password",
          "Fee Started Price": "Fee Started Price",
          "Select Category": "Select Category",
          "Address": "Address",
          "Zipcode": "Zipcode",
          "Select Latitude & Longitude from here :":
              "Select Latitude & Longitude from here :",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.":
              "Please enter valid Latitude & Longitude otherwise app may not work properly.",
          "Your Latitude": "Your Latitude",
          "Your Longitude": "Your Longitude",
          "No Internet Connection": "No Internet Connection",
          "Developed By ": "Developed By ",
          "Select Stylist": "Select Stylist",
          "Appoinment": "Appoinment",
          "Profile": "Profile",
          "Forgot Password ?": "Forgot Password ?",
          "Send OTP": "Send OTP",
          "Gereate Password": "Gereate Password",
          "New Password": "New Password",
          "Update Password": "Update Password",
          "All fields are required!": "All fields are required!",
          "Please select specialist": "Please select specialist",
          "Please wait": "Please wait",
          "Save Packages": "Save Packages",
          "packages update !": "packages update !",
          "Discount must be less than 100": "Discount must be less than 100",
          "Services Added !": "Services Added !",
          "services update !": "services update !",
          "Please select time": "Please select time",
          "Already exist": "Already exist",
          "Slots are empty": "Slots are empty",
          "Save Specialist": "Save Specialist",
          "Already added": "Already added",
          "January": "January",
          "February": "February",
          "March": "March",
          "April": "April",
          "May": "May",
          "June": "June",
          "July": "July",
          "August": "August",
          "September": "September",
          "October": "October",
          "November": "November",
          "December": "December",
          "Created": "Created",
          "Accepted": "Accepted",
          "Rejected": "Rejected",
          "Ongoing": "Ongoing",
          "Completed": "Completed",
          "Cancelled": "Cancelled",
          "Refunded": "Refunded",
          "Delayed": "Delayed",
          "Panding Payment": "Panding Payment",
          "New message received": "New message received",
          "Select Your Cities !": "Select Your Cities !",
          "City Updated": "City Updated",
          "All fields are required": "All fields are required",
          "Email is not valid": "Email is not valid",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon":
              "We have received your request, we will respond on your issue soon",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Please select category": "Please select category",
          "Save Products": "Save Products",
          "Gallery Updated": "Gallery Updated",
          "Please select one of the categories":
              "Please select one of the categories",
          "Categories Updated": "Categories Updated",
          "Update Salon": "Update Salon",
          "Access denied": "Access denied",
          "Something went wrong": "Something went wrong",
          "Phone Number is required": "Phone Number is required",
          "Something went wrong while signup":
              "Something went wrong while signup",
          "Verification": "Verification",
          "We have sent verification code on":
              "We have sent verification code on",
          "COD": "COD",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Cancelled by user": "Cancelled by user",
          "Status Updated": "Status Updated",
          "New Notificaiton": "New Notificaiton",
          "Your Appointment status is Changed":
              "Your Appointment status is Changed",
          "Choose": "Choose",
          "Complaints": "Complaints",
          "Chat": "Chat",
          "Call": "Call",
          "item remove successfully": "item remove successfully",
          "Updated": "Updated",
          "Your order status is Changed": "Your order status is Changed",
          "Select Service": "Select Service",
          "Products Categories": "Products Categories",
          "Your Email is Verified": "Your Email is Verified",
          "Phone number is required": "Phone number is required",
          "Please verify email": "Please verify email",
          "Please verify phone number": "Please verify phone number",
          "Please upload your cover photo": "Please upload your cover photo",
          "password does not match": "password does not match",
          "Success!": "Success!",
          "Your Request is submitted": "Your Request is submitted",
          "Slot Remove Successfully": "Slot Remove Successfully",
          "All Fields Are Required": "All Fields Are Required",
          "Password mismatch": "Password mismatch",
          "Password Updated": "Password Updated"
        },
        "hi_IN": {
          "Add Packages": "पैकेज जोड़ें",
          "Choose From": "से चुनें",
          "Camera": "कैमरा",
          "Gallery": "गेलरी",
          "Cancel": "रद्द करना",
          "Select Categories": "श्रेणियों का चयन करें",
          "Select Specialist": "विशेषज्ञ का चयन करें",
          "Packages Name": "पैकेज का नाम",
          "Price": "कीमत",
          "Discount": "छूट",
          "Sell Price": "विक्रय मूल्य",
          "Descriptions": "विवरण",
          "Duration": "अवधि",
          "Upload More Image": "अधिक छवि अपलोड करें",
          "ADD PACKAGES": "पैकेज जोड़ें",
          "UPDATE PACKAGES": "अद्यतन पैकेज",
          "Add Service": "सेवा जोड़ें",
          "Service Name": "सेवा का नाम",
          "Categories": "श्रेणियाँ",
          "Service Price": "सेवा मूल्य",
          "Discount %": "छूट %",
          "Service Duration": "सेवा अवधि",
          "Description": "विवरण",
          "Available": "उपलब्ध",
          "Hide": "छिपाना",
          "Status": "दर्जा",
          "SUBMIT": "प्रस्तुत",
          "UPDATE": "अपडेट करें",
          "Add Slots": "स्लॉट जोड़ें",
          "Sunday": "रविवार",
          "Monday": "सोमवार",
          "Tuesday": "मंगलवार",
          "Wednesday": "बुधवार",
          "Thursday": "गुरुवार",
          "Friday": "शुक्रवार",
          "Saturday": "शनिवार",
          "Open Time": "खुला समय",
          "Close Time": "बंद होने का समय",
          "Are you sure": "क्या आपको यकीन है",
          "to delete this slot ?": "इस स्लॉट को हटाने के लिए?",
          "Delete": "मिटाना",
          "Add": "जोड़ें",
          "Save & Submit": "सहेजें और सबमिट करें",
          "Add Stylist": "स्टाइलिस्ट जोड़ें",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Add Timing": "समय जोड़ें",
          "Save": "बचाना",
          "Update": "अद्यतन",
          "Daily": "रोज",
          "Monthly": "महीने के",
          "Yearly": "सालाना",
          "Analyze": "विश्लेषण",
          "Appointment": "नियुक्ति",
          "Products Order": "उत्पाद आदेश",
          "Earnings": "आय",
          "Total": "कुल",
          "Average": "औसत",
          "Day": "दिन",
          "Bookings": "बुकिंग के",
          "Months": "महीने",
          "Orders": "आदेश",
          "Total number of bookings": "कुल बुकिंग",
          "Total number of orders": "आदेशों की कुल संख्या",
          "Appointments History": "नियुक्ति इतिहास",
          "New": "नया",
          "Old": "पुराना",
          "At Salon": "सैलून में",
          "Appointments ID #": "नियुक्ति आईडी #",
          "Services": "सेवाएं",
          "Packages": "संकुल",
          "Grand Total :": "कुल योग :",
          "Appointment at :": "नियुक्ति पर:",
          "No New Appointment Found!": "कोई नई नियुक्ति नहीं मिली!",
          "No Past Appointment Found!": "कोई पिछली नियुक्ति नहीं मिली!",
          "Calendar": "पंचांग",
          "No Appointment Found!": "कोई नियुक्ति नहीं मिली!",
          "Message...": "संदेश...",
          "Select Cities": "शहरों का चयन करें",
          "Cancle": "चकमा देना",
          "Submit": "प्रस्तुत करना",
          "Contact Us": "संपर्क करें",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Create Products": "उत्पाद बनाएं",
          "Update Products": "अद्यतन उत्पाद",
          "Select Subcategories": "उपश्रेणियों का चयन करें",
          "Sub Categories": "उप श्रेणियां",
          "Products Name": "उत्पादों का नाम",
          "Products Price": "उत्पादों की कीमत",
          "in Offers": "प्रस्ताव में",
          "in Stock": "स्टॉक में",
          "in Home": "घर में",
          "in Single": "एकल में",
          "in Gram": "ग्राम में",
          "Gram Value": "ग्राम मूल्य",
          "in KG": "केजी में",
          "KG Value": "किग्रा मूल्य",
          "in Liter": "लीटर में",
          "Liter Value": "लीटर मूल्य",
          "in PCs": "पीसीएस में",
          "PCs Value": "पीसीएस मूल्य",
          "in ML": "एमएल में",
          "ML Value": "एमएल मूल्य",
          "Expired Date": "अवधि समाप्त तारीख",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network": "नेटवर्क से कनेक्ट नहीं हो सका",
          "Please check and try again": "कृपया जाँच करें और पुनः प्रयास करें",
          "retry": "पुन: प्रयास करें",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "Gallary": "गैलरी",
          "Upload Image": "तस्विर अपलोड करना",
          "Update Images": "अद्यतन चित्र",
          "Order History": "आदेश इतिहास",
          "Order Id #": "आदेश ID #",
          "Order At : ": "आदेश पर:",
          "Grand Total : ": "कुल योग :",
          "No New Orders Found!": "कोई नया आदेश नहीं मिला!",
          "No Past Orders Found!": "कोई अतीत के आदेश नहीं मिले!",
          "Messages": "संदेशों",
          "Select Individual Categories": "व्यक्तिगत श्रेणियों का चयन करें",
          "Brief Of Salon": "सैलून का संक्षिप्त विवरण",
          "Enter Address..": "पता लिखिए..",
          "Select": "चुनना",
          "ZIP Code": "पिन कोड",
          "Latitude": "अक्षांश",
          "Longitude": "देशान्तर",
          "Have Popular ?": "लोकप्रिय है?",
          "Have Shop ?": "दुकान है?",
          "Have Home ?": "घर हो ?",
          "Opening Hour": "खुलने का समय",
          "Edit": "संपादन करना",
          "Languages": "बोली",
          "Welcome": "स्वागत",
          "Login With Your Account": "अपने खाते के साथ लॉगिन करें",
          "Email ID": "ईमेल आईडी",
          "Password": "पासवर्ड",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "LOG IN": "लॉग इन करें",
          "Don't have an Account? Sign Up": "कोई खाता नहीं है? साइन अप करें",
          "Mobile Number": "मोबाइल नंबर",
          "Appointments No #": "नियुक्ति नहीं #",
          "Service At": "सेवा करना",
          "Booking Date & Time": "बुकिंग दिनांक और समय",
          "Booking Date": "बुक करने की तिथि",
          "Booking Time": "बुकिंग समय",
          "Pricing": "मूल्य निर्धारण",
          "Wallet Discount": "बटुआ छूट",
          "Distance Cost": "दूरी लागत",
          "Service Tax": "सेवा कर",
          "Payment": "भुगतान",
          "Total Amount": "कुल राशि",
          "Your Appoinments Status": "आपकी appoinments स्थिति",
          "Accept": "स्वीकार करना",
          "Decline": "पतन",
          "Update Status": "नवीनतम स्थिति",
          "Select Packages": "पैकेज का चयन करें",
          "and more": "और अधिक",
          "Add New": "नया जोड़ो",
          "to delete Slots ?": "स्लॉट को हटाने के लिए?",
          "Order No #": "आदेश संख्या #",
          "Delivery Address": "डिलिवरी का पता",
          "Order Date": "आर्डर की तारीख",
          "Your Order Status": "आपकी ऑर्डर की स्थिति",
          "Products": "उत्पादों",
          "Search for Salon, Services....":
              "सैलून, सेवाओं के लिए खोज करें ...।",
          "Enter Salon Name": "सैलून नाम दर्ज करें",
          "Have Multiple Stylist ?": "कई स्टाइलिस्ट हैं?",
          " Reviews) ": "समीक्षा)",
          "Your Profile": "आपकी प्रोफ़ाइल",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Chats": "चैट",
          "Review": "समीक्षा",
          "Slots": "स्लॉट्स",
          "Stylist": "स्टाइलिस्ट",
          "History": "इतिहास",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "Help": "मदद करना",
          "Privacy Policy": "गोपनीयता नीति",
          "Terms & Conditions": "नियम एवं शर्तें",
          "About us": "हमारे बारे में",
          "About": "के बारे में",
          "Logout": "लॉग आउट",
          "Served Category": "सेवा श्रेणी",
          "All Reviews": "सभी समीक्षाएँ",
          "Select Salon Categories": "सैलून श्रेणियों का चयन करें",
          "Select Services": "सेवाओं का चयन करें",
          "Select Shop Categories": "दुकान श्रेणियों का चयन करें",
          "Select Shop Subcategories": "दुकान उपश्रेणियों का चयन करें",
          "Send Register Request": "रजिस्टर अनुरोध भेजें",
          "Next": "अगला",
          "Previews": "झलकियां",
          "Select your type": "अपने प्रकार का चयन करें",
          "Salon": "सैलून",
          "Individual": "व्यक्तिगत",
          "Email": "ईमेल",
          "Verify": "सत्यापित करना",
          "Verified": "सत्यापित",
          "Search": "खोज",
          "Start typing to search": "खोज करने के लिए टाइप करना शुरू करें",
          "Code": "कोड",
          "Phone": "फ़ोन",
          "Salon Name": "सैलून नाम",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Fee Started Price": "शुल्क शुरू किया मूल्य",
          "Select Category": "श्रेणी चुनना",
          "Address": "पता",
          "Zipcode": "पिन कोड",
          "Select Latitude & Longitude from here :":
              "यहाँ से अक्षांश और देशांतर का चयन करें:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.":
              "कृपया मान्य अक्षांश और देशांतर दर्ज करें अन्यथा ऐप ठीक से काम नहीं कर सकता है।",
          "Your Latitude": "आपका अक्षांश",
          "Your Longitude": "आपका देशांतर",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Developed By ": "द्वारा विकसित",
          "Select Stylist": "स्टाइलिस्ट का चयन करें",
          "Appoinment": "नियुक्ति",
          "Profile": "प्रोफ़ाइल",
          "Forgot Password ?": "पासवर्ड भूल गए ?",
          "Send OTP": "OTP भेजें",
          "Gereate Password": "Gereate पासवर्ड",
          "New Password": "नया पासवर्ड",
          "Update Password": "पासवर्ड अपडेट करें",
          "All fields are required!": "सभी फ़ील्ड आवश्यक हैं!",
          "Please select specialist": "कृपया विशेषज्ञ का चयन करें",
          "Please wait": "कृपया प्रतीक्षा करें",
          "Save Packages": "पैकेज सहेजें",
          "packages update !": "पैकेज अपडेट!",
          "Discount must be less than 100": "छूट 100 से कम होनी चाहिए",
          "Services Added !": "सेवाओं को जोड़ा गया!",
          "services update !": "सेवा अद्यतन!",
          "Please select time": "कृपया समय चुनें",
          "Already exist": "पहले से ही मौजूद",
          "Slots are empty": "स्लॉट खाली हैं",
          "Save Specialist": "विशेषज्ञ सहेजें विशेषज्ञ",
          "Already added": "पहले से ही जोड़ा",
          "January": "जनवरी",
          "February": "फ़रवरी",
          "March": "मार्च",
          "April": "अप्रैल",
          "May": "मई",
          "June": "जून",
          "July": "जुलाई",
          "August": "अगस्त",
          "September": "सितंबर",
          "October": "अक्टूबर",
          "November": "नवंबर",
          "December": "दिसंबर",
          "Created": "बनाया था",
          "Accepted": "को स्वीकृत",
          "Rejected": "अस्वीकृत",
          "Ongoing": "चल रहे",
          "Completed": "पूरा हुआ",
          "Cancelled": "रद्द",
          "Refunded": "वापसी की गई है",
          "Delayed": "देर से",
          "Panding Payment": "अदायगी",
          "New message received": "नया संदेश प्राप्त हुआ",
          "Select Your Cities !": "अपने शहरों का चयन करें!",
          "City Updated": "शहर अपडेट किया गया",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल मिला है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon":
              "हमें आपका अनुरोध मिला है, हम आपके मुद्दे पर जल्द ही जवाब देंगे",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी",
          "Okay": "ठीक",
          "Please select category": "कृपया श्रेणी का चयन करें",
          "Save Products": "उत्पाद सहेजें",
          "Gallery Updated": "गैलरी अद्यतित",
          "Please select one of the categories":
              "कृपया श्रेणियों में से एक का चयन करें",
          "Categories Updated": "अद्यतित श्रेणियां",
          "Update Salon": "अद्यतन सैलून",
          "Access denied": "पहुंच अस्वीकृत",
          "Something went wrong": "कुछ गलत हो गया",
          "Phone Number is required": "फोन नंबर की आवश्यकता है",
          "Something went wrong while signup": "साइनअप करते समय कुछ गलत हुआ",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड भेजा है",
          "COD": "सीओडी",
          "Stripe": "पट्टी",
          "PayPal": "पेपैल",
          "Paytm": "Paytm",
          "Razorpay": "रज़ोरपे",
          "Instamojo": "इंस्टैमोजो",
          "Paystack": "अदायगी",
          "Flutterwave": "फड़फड़ाना",
          "Cancelled by user": "उपयोगकर्ता द्वारा रद्द",
          "Status Updated": "अद्यतन की गई स्थिति",
          "New Notificaiton": "New notificaiton",
          "Your Appointment status is Changed":
              "आपकी नियुक्ति की स्थिति बदल गई है",
          "Choose": "चुनना",
          "Complaints": "शिकायतों",
          "Chat": "बात करना",
          "Call": "बुलाना",
          "item remove successfully": "आइटम सफलतापूर्वक निकालें",
          "Updated": "अद्यतन",
          "Your order status is Changed": "आपकी ऑर्डर की स्थिति बदल गई है",
          "Select Service": "सेवा का चयन करें",
          "Products Categories": "उत्पाद श्रेणियां",
          "Your Email is Verified": "आपका ईमेल सत्यापित है",
          "Phone number is required": "फोन नंबर की आवश्यकता है",
          "Please verify email": "कृपया ईमेल सत्यापित करें",
          "Please verify phone number": "कृपया फ़ोन नंबर सत्यापित करें",
          "Please upload your cover photo": "कृपया अपना कवर फोटो अपलोड करें",
          "password does not match": "पासवर्ड मैच नहीं कर रहा है",
          "Success!": "सफलता!",
          "Your Request is submitted": "आपका अनुरोध सबमिट किया गया है",
          "Slot Remove Successfully": "स्लॉट सफलतापूर्वक निकालें",
          "All Fields Are Required": "सभी फ़ील्ड आवश्यक हैं",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Password Updated": "पासवर्ड अपडेट किया गया"
        },
        "es_DE": {
          "Add Packages": "Agregar paquetes",
          "Choose From": "Escoge de",
          "Camera": "Cámara",
          "Gallery": "Galería",
          "Cancel": "Cancelar",
          "Select Categories": "Seleccionar categorías",
          "Select Specialist": "Seleccionar especialista",
          "Packages Name": "Nombre de los paquetes",
          "Price": "Precio",
          "Discount": "Descuento",
          "Sell Price": "Precio de venta",
          "Descriptions": "Descripciones",
          "Duration": "Duración",
          "Upload More Image": "Subir más imagen",
          "ADD PACKAGES": "Agregar paquetes",
          "UPDATE PACKAGES": "Actualizar paquetes",
          "Add Service": "Agregar servicio",
          "Service Name": "Nombre del Servicio",
          "Categories": "Categorías",
          "Service Price": "Precio de servicio",
          "Discount %": "Descuento %",
          "Service Duration": "Duración del servicio",
          "Description": "Descripción",
          "Available": "Disponible",
          "Hide": "Ocultar",
          "Status": "Estado",
          "SUBMIT": "ENVIAR",
          "UPDATE": "ACTUALIZAR",
          "Add Slots": "Agregar ranuras",
          "Sunday": "Domingo",
          "Monday": "Lunes",
          "Tuesday": "martes",
          "Wednesday": "miércoles",
          "Thursday": "jueves",
          "Friday": "Viernes",
          "Saturday": "sábado",
          "Open Time": "Tiempo de apertura",
          "Close Time": "Hora de cierre",
          "Are you sure": "Está seguro",
          "to delete this slot ?": "para eliminar esta ranura?",
          "Delete": "Borrar",
          "Add": "Agregar",
          "Save & Submit": "Guardar y enviar",
          "Add Stylist": "Agregar estilista",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Add Timing": "Agregar tiempo",
          "Save": "Ahorrar",
          "Update": "Actualizar",
          "Daily": "Diariamente",
          "Monthly": "Mensual",
          "Yearly": "Anual",
          "Analyze": "Analizar",
          "Appointment": "Cita",
          "Products Order": "Pedido de productos",
          "Earnings": "Ganancias",
          "Total": "Total",
          "Average": "Promedio",
          "Day": "Día",
          "Bookings": "Reservaciones",
          "Months": "Meses",
          "Orders": "Pedidos",
          "Total number of bookings": "Número total de reservas",
          "Total number of orders": "Número total de pedidos",
          "Appointments History": "Historial de citas",
          "New": "Nueva",
          "Old": "Antigua",
          "At Salon": "En salón",
          "Appointments ID #": "ID de cita #",
          "Services": "Servicios",
          "Packages": "Paquetes",
          "Grand Total :": "Gran total :",
          "Appointment at :": "Cita en:",
          "No New Appointment Found!": "¡No se encontró una nueva cita!",
          "No Past Appointment Found!": "¡No se encontró una cita pasada!",
          "Calendar": "Calendario",
          "No Appointment Found!": "¡No se encontró cita!",
          "Message...": "Mensaje...",
          "Select Cities": "Seleccionar ciudades",
          "Cancle": "Atacar",
          "Submit": "Enviar",
          "Contact Us": "Contáctenos",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Create Products": "Crear productos",
          "Update Products": "Actualizar productos",
          "Select Subcategories": "Seleccionar subcategorías",
          "Sub Categories": "Subcategas",
          "Products Name": "Nombre del producto",
          "Products Price": "Precio de los productos",
          "in Offers": "en ofertas",
          "in Stock": "en stock",
          "in Home": "en el hogar",
          "in Single": "en soltero",
          "in Gram": "en gramo",
          "Gram Value": "Valor gramo",
          "in KG": "en kg",
          "KG Value": "Valor kg",
          "in Liter": "con litro",
          "Liter Value": "Valor de litro",
          "in PCs": "en PCS",
          "PCs Value": "Valor de las PCS",
          "in ML": "en ml",
          "ML Value": "Valor ml",
          "Expired Date": "Fecha de vencimiento",
          "Connection Failed": "La conexión falló",
          "Could not connect to network": "No se pudo conectar a la red",
          "Please check and try again": "Por favor revisa e intenta de nuevo",
          "retry": "rever",
          "Verify your phone number": "verifica tu numero de telefono",
          "Gallary": "Galato",
          "Upload Image": "Cargar imagen",
          "Update Images": "Actualizar imágenes",
          "Order History": "Historial de pedidos",
          "Order Id #": "Solicitar ID #",
          "Order At : ": "Ordenar en:",
          "Grand Total : ": "Gran total :",
          "No New Orders Found!": "¡No se encontraron nuevos pedidos!",
          "No Past Orders Found!": "¡No se encontraron órdenes pasadas!",
          "Messages": "Mensajes",
          "Select Individual Categories": "Seleccionar categorías individuales",
          "Brief Of Salon": "Breve de salón",
          "Enter Address..": "Ingresa la direccion..",
          "Select": "Seleccione",
          "ZIP Code": "Código postal",
          "Latitude": "Latitud",
          "Longitude": "Longitud",
          "Have Popular ?": "¿Tienes popular?",
          "Have Shop ?": "¿Tiene tienda?",
          "Have Home ?": "Tienen hogar ?",
          "Opening Hour": "Hora de apertura",
          "Edit": "Editar",
          "Languages": "Lengua",
          "Welcome": "Bienvenidas",
          "Login With Your Account": "Inicie sesión con su cuenta",
          "Email ID": "Identificación de correo",
          "Password": "Clave",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "LOG IN": "INICIAR SESIÓN",
          "Don't have an Account? Sign Up":
              "¿No tienes una cuenta? Inscribirse",
          "Mobile Number": "Número de teléfono móvil",
          "Appointments No #": "Citas no #",
          "Service At": "Servicio",
          "Booking Date & Time": "Fecha de reserva y hora",
          "Booking Date": "Fecha para registrarse",
          "Booking Time": "Tiempo de reserva",
          "Pricing": "Fijación",
          "Wallet Discount": "Descuento de billetera",
          "Distance Cost": "Costo de distancia",
          "Service Tax": "Impuesto de servicio",
          "Payment": "Pago",
          "Total Amount": "Cantidad total",
          "Your Appoinments Status": "El estado de su recopilación",
          "Accept": "Aceptar",
          "Decline": "Rechazar",
          "Update Status": "Estado de actualización",
          "Select Packages": "Seleccionar paquetes",
          "and more": "y más",
          "Add New": "Agregar nuevo",
          "to delete Slots ?": "para eliminar las ranuras?",
          "Order No #": "N º de pedido #",
          "Delivery Address": "Dirección de entrega",
          "Order Date": "Fecha de orden",
          "Your Order Status": "El estado de su pedido",
          "Products": "Productos",
          "Search for Salon, Services....": "Buscar salón, servicios ....",
          "Enter Salon Name": "Ingrese el nombre del salón",
          "Have Multiple Stylist ?": "¿Tiene múltiples estilistas?",
          " Reviews) ": "Reseñas)",
          "Your Profile": "Tu perfil",
          "Edit Profile": "Editar perfil",
          "Chats": "Chatas",
          "Review": "Revisar",
          "Slots": "Ranura",
          "Stylist": "Estilista",
          "History": "Historia",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "Help": "Ayuda",
          "Privacy Policy": "Política de privacidad",
          "Terms & Conditions": "Términos y condiciones",
          "About us": "Sobre nosotros",
          "About": "Sobre",
          "Logout": "Cerrar sesión",
          "Served Category": "Categoría servida",
          "All Reviews": "Todas las reseñas",
          "Select Salon Categories": "Seleccionar categorías de salón",
          "Select Services": "Seleccione Servicios",
          "Select Shop Categories": "Seleccionar categorías de tiendas",
          "Select Shop Subcategories": "Seleccionar subcategorías de tiendas",
          "Send Register Request": "Enviar solicitud de registro",
          "Next": "Próxima",
          "Previews": "Avances",
          "Select your type": "Seleccione su tipo",
          "Salon": "Salón",
          "Individual": "Individual",
          "Email": "Correo electrónico",
          "Verify": "Verificar",
          "Verified": "Verificada",
          "Search": "Búsqueda",
          "Start typing to search": "Empiece a escribir para buscar",
          "Code": "Código",
          "Phone": "Teléfono",
          "Salon Name": "Nombre del salón",
          "Confirm Password": "Confirmar contraseña",
          "Fee Started Price": "Precio de tarifa iniciada",
          "Select Category": "selecciona una categoría",
          "Address": "Dirección",
          "Zipcode": "Código postal",
          "Select Latitude & Longitude from here :":
              "Seleccione Latitud y Longitud desde aquí:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.":
              "Ingrese la latitud y longitud válidas, de lo contrario la aplicación puede no funcionar correctamente.",
          "Your Latitude": "Tu latitud",
          "Your Longitude": "Tu longitud",
          "No Internet Connection": "Sin conexión a Internet",
          "Developed By ": "Desarrollado por",
          "Select Stylist": "Seleccionar estilista",
          "Appoinment": "Componente",
          "Profile": "Perfil",
          "Forgot Password ?": "Has olvidado tu contraseña ?",
          "Send OTP": "Enviar OTP",
          "Gereate Password": "Contraseña de gereate",
          "New Password": "Nueva contraseña",
          "Update Password": "Actualiza contraseña",
          "All fields are required!": "¡Todos los campos son obligatorios!",
          "Please select specialist": "Seleccione especialista",
          "Please wait": "Espere por favor",
          "Save Packages": "Guardar paquetes",
          "packages update !": "¡Actualización de paquetes!",
          "Discount must be less than 100":
              "El descuento debe ser menos de 100",
          "Services Added !": "¡Servicios agregados!",
          "services update !": "¡Actualización de servicios!",
          "Please select time": "Seleccione el tiempo",
          "Already exist": "Ya existe",
          "Slots are empty": "Las ranuras están vacías",
          "Save Specialist": "Guardar especialista",
          "Already added": "Ya agregado",
          "January": "enero",
          "February": "Febrero",
          "March": "Marzo",
          "April": "Abril",
          "May": "Mayo",
          "June": "Junio",
          "July": "Julio",
          "August": "Agosto",
          "September": "Septiembre",
          "October": "Octubre",
          "November": "Noviembre",
          "December": "Diciembre",
          "Created": "Creada",
          "Accepted": "Aceptada",
          "Rejected": "Rechazada",
          "Ongoing": "En curso",
          "Completed": "Terminada",
          "Cancelled": "Cancelada",
          "Refunded": "Reintegrada",
          "Delayed": "Demorada",
          "Panding Payment": "Pago",
          "New message received": "Nuevo mensaje recibido",
          "Select Your Cities !": "¡Seleccione sus ciudades!",
          "City Updated": "Ciudad actualizada",
          "All fields are required": "Todos los campos son obligatorios",
          "Email is not valid": "El correo no es válido",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido un nuevo correo",
          "New Contact Details": "Nuevos datos de contacto",
          "We have received your request, we will respond on your issue soon":
              "Hemos recibido su solicitud, pronto responderemos sobre su problema.",
          "Alert!": "¡Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "Okay": "De acuerdo",
          "Please select category": "Seleccione la categoría",
          "Save Products": "Guardar productos",
          "Gallery Updated": "Galería actualizada",
          "Please select one of the categories":
              "Seleccione una de las categorías",
          "Categories Updated": "Categorías actualizadas",
          "Update Salon": "Actualizar salón",
          "Access denied": "Acceso denegado",
          "Something went wrong": "Algo salió mal",
          "Phone Number is required": "Se requiere número de teléfono",
          "Something went wrong while signup":
              "Algo salió mal mientras se registra",
          "Verification": "Verificación",
          "We have sent verification code on":
              "Hemos enviado código de verificación en",
          "COD": "BACALAO",
          "Stripe": "Raya",
          "PayPal": "Paypal",
          "Paytm": "Paytm",
          "Razorpay": "Razonpay",
          "Instamojo": "Instamos",
          "Paystack": "Paystack",
          "Flutterwave": "Flutero",
          "Cancelled by user": "Cancelado por usuario",
          "Status Updated": "Estado actualizado",
          "New Notificaiton": "Nuevo Notificaiton",
          "Your Appointment status is Changed":
              "El estado de su cita se cambia",
          "Choose": "Elegir",
          "Complaints": "Quejas",
          "Chat": "Charlar",
          "Call": "Llamar",
          "item remove successfully": "Elemento elimina con éxito",
          "Updated": "Actualizada",
          "Your order status is Changed": "El estado de su pedido se cambia",
          "Select Service": "Seleccione Servicio",
          "Products Categories": "Categorías de productos",
          "Your Email is Verified": "Su correo electrónico está verificado",
          "Phone number is required": "Se requiere número de teléfono",
          "Please verify email": "Por favor verifique el correo electrónico",
          "Please verify phone number": "Verifique el número de teléfono",
          "Please upload your cover photo": "Sube tu foto de portada",
          "password does not match": "las contraseñas no coinciden",
          "Success!": "¡Éxito!",
          "Your Request is submitted": "Su solicitud se envía",
          "Slot Remove Successfully": "Ranura eliminar con éxito",
          "All Fields Are Required": "Todos los campos son obligatorios",
          "Password mismatch": "Contraseña no coincide",
          "Password Updated": "Contraseña actualiza"
        },
        "ar_AE": {
          "Add Packages": "إضافة الحزم",
          "Choose From": "اختر من",
          "Camera": "آلة تصوير",
          "Gallery": "صالة عرض",
          "Cancel": "يلغي",
          "Select Categories": "اختيار الفئات",
          "Select Specialist": "حدد متخصص",
          "Packages Name": "اسم الحزم",
          "Price": "سعر",
          "Discount": "تخفيض",
          "Sell Price": "سعر البيع",
          "Descriptions": "الأوصاف",
          "Duration": "مدة",
          "Upload More Image": "تحميل المزيد من الصورة",
          "ADD PACKAGES": "إضافة الحزم",
          "UPDATE PACKAGES": "تحديث الحزم",
          "Add Service": "أضف الخدمة",
          "Service Name": "اسم الخدمة",
          "Categories": "فئات",
          "Service Price": "سعر الخدمة",
          "Discount %": "تخفيض ٪",
          "Service Duration": "مدة الخدمة",
          "Description": "وصف",
          "Available": "متوفرة",
          "Hide": "يخفي",
          "Status": "حالة",
          "SUBMIT": "إرسال",
          "UPDATE": "تحديث",
          "Add Slots": "أضف فتحات",
          "Sunday": "الأحد",
          "Monday": "الاثنين",
          "Tuesday": "يوم الثلاثاء",
          "Wednesday": "الأربعاء",
          "Thursday": "يوم الخميس",
          "Friday": "جمعة",
          "Saturday": "السبت",
          "Open Time": "وقت متاح",
          "Close Time": "وقت الاغلاق",
          "Are you sure": "هل أنت واثق",
          "to delete this slot ?": "لحذف هذه الفتحة؟",
          "Delete": "حذف",
          "Add": "يضيف",
          "Save & Submit": "حفظ وتقديم",
          "Add Stylist": "أضف المصمم",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Add Timing": "إضافة توقيت",
          "Save": "يحفظ",
          "Update": "تحديث",
          "Daily": "اليومي",
          "Monthly": "شهريا",
          "Yearly": "سنوي",
          "Analyze": "تحليل",
          "Appointment": "ميعاد",
          "Products Order": "طلب المنتجات",
          "Earnings": "الأرباح",
          "Total": "المجموع",
          "Average": "متوسط",
          "Day": "يوم",
          "Bookings": "الحجوزات",
          "Months": "شهور",
          "Orders": "الطلب #٪ s",
          "Total number of bookings": "إجمالي عدد الحجوزات",
          "Total number of orders": "إجمالي عدد الطلبات",
          "Appointments History": "تاريخ المواعيد",
          "New": "جديد",
          "Old": "قديم",
          "At Salon": "في صالون",
          "Appointments ID #": "معرف المواعيد #",
          "Services": "خدمات",
          "Packages": "حزم",
          "Grand Total :": "المبلغ الإجمالي :",
          "Appointment at :": "الموعد في:",
          "No New Appointment Found!": "لم يتم العثور على موعد جديد!",
          "No Past Appointment Found!": "لم يتم العثور على موعد سابق!",
          "Calendar": "تقويم",
          "No Appointment Found!": "لم يتم العثور على موعد!",
          "Message...": "رسالة...",
          "Select Cities": "حدد المدن",
          "Cancle": "Cancle",
          "Submit": "يُقدِّم",
          "Contact Us": "اتصل بنا",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Create Products": "إنشاء منتجات",
          "Update Products": "تحديث المنتجات",
          "Select Subcategories": "حدد الفئات الفرعية",
          "Sub Categories": "الفئات الفرعية",
          "Products Name": "اسم المنتجات",
          "Products Price": "سعر المنتجات",
          "in Offers": "في العروض",
          "in Stock": "في الأوراق المالية",
          "in Home": "في المنزل",
          "in Single": "بمفرده",
          "in Gram": "في غرام",
          "Gram Value": "قيمة غرام",
          "in KG": "في كجم",
          "KG Value": "قيمة كجم",
          "in Liter": "في لتر",
          "Liter Value": "قيمة لتر",
          "in PCs": "في أجهزة الكمبيوتر",
          "PCs Value": "قيمة أجهزة الكمبيوتر",
          "in ML": "في مل",
          "ML Value": "قيمة مل",
          "Expired Date": "منتهي الصلاحية",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network": "لا يمكن الاتصال بالشبكة",
          "Please check and try again": "يرجى مراجعة وحاول مرة أخرى",
          "retry": "إعادة المحاولة",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "Gallary": "جالاري",
          "Upload Image": "تحميل الصور",
          "Update Images": "تحديث الصور",
          "Order History": "تاريخ الطلب",
          "Order Id #": "رقم التعريف الخاص بالطلب #",
          "Order At : ": "النظام في:",
          "Grand Total : ": "المبلغ الإجمالي :",
          "No New Orders Found!": "لم يتم العثور على أوامر جديدة!",
          "No Past Orders Found!": "لم يتم العثور على أوامر سابقة!",
          "Messages": "رسائل",
          "Select Individual Categories": "حدد الفئات الفردية",
          "Brief Of Salon": "موجز من صالون",
          "Enter Address..": "أدخل العنوان..",
          "Select": "يختار",
          "ZIP Code": "الرمز البريدي",
          "Latitude": "خط العرض",
          "Longitude": "خط الطول",
          "Have Popular ?": "هل لديك شعبية؟",
          "Have Shop ?": "هل لديك متجر؟",
          "Have Home ?": "هل لديك منزل؟",
          "Opening Hour": "ساعة الافتتاح",
          "Edit": "يحرر",
          "Languages": "اللغات",
          "Welcome": "أهلا وسهلا",
          "Login With Your Account": "تسجيل الدخول بحسابك",
          "Email ID": "عنوان الايميل",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "LOG IN": "تسجيل الدخول",
          "Don't have an Account? Sign Up": "ليس لديك حساب؟ اشتراك",
          "Mobile Number": "رقم الهاتف المحمول",
          "Appointments No #": "المواعيد لا #",
          "Service At": "الخدمة في",
          "Booking Date & Time": "تاريخ الحجز والوقت",
          "Booking Date": "تاريخ الحجز",
          "Booking Time": "وقت الحجز",
          "Pricing": "التسعير",
          "Wallet Discount": "خصم محفظة",
          "Distance Cost": "تكلفة المسافة",
          "Service Tax": "ضريبة الخدمة",
          "Payment": "دفع",
          "Total Amount": "المبلغ الإجمالي",
          "Your Appoinments Status": "حالة appoinments الخاصة بك",
          "Accept": "قبول",
          "Decline": "انخفاض",
          "Update Status": "تحديث الحالة",
          "Select Packages": "حدد الحزم",
          "and more": "و اكثر",
          "Add New": "اضف جديد",
          "to delete Slots ?": "لحذف الفتحات؟",
          "Order No #": "طلب رقم #",
          "Delivery Address": "عنوان التسليم",
          "Order Date": "تاريخ الطلب",
          "Your Order Status": "حالة طلبك",
          "Products": "منتجات",
          "Search for Salon, Services....": "ابحث عن الصالون والخدمات ....",
          "Enter Salon Name": "أدخل اسم الصالون",
          "Have Multiple Stylist ?": "هل لديك مصمم مصمم متعدد؟",
          " Reviews) ": "المراجعات)",
          "Your Profile": "ملفك الشخصي",
          "Edit Profile": "تعديل الملف الشخصي",
          "Chats": "الدردشات",
          "Review": "إعادة النظر",
          "Slots": "فتحات",
          "Stylist": "حلاق",
          "History": "تاريخ",
          "Frequently Asked Questions": "أسئلة مكررة",
          "Help": "مساعدة",
          "Privacy Policy": "سياسة الخصوصية",
          "Terms & Conditions": "البنود و الظروف",
          "About us": "معلومات عنا",
          "About": "حول",
          "Logout": "تسجيل خروج",
          "Served Category": "خدم فئة",
          "All Reviews": "جميع المراجعات",
          "Select Salon Categories": "حدد فئات الصالون",
          "Select Services": "حدد الخدمات",
          "Select Shop Categories": "حدد فئات المتجر",
          "Select Shop Subcategories": "حدد المتجر الفئات الفرعية",
          "Send Register Request": "إرسال طلب السجل",
          "Next": "التالي",
          "Previews": "معاينات",
          "Select your type": "حدد النوع الخاص بك",
          "Salon": "صالون",
          "Individual": "الفرد",
          "Email": "البريد الإلكتروني",
          "Verify": "يؤكد",
          "Verified": "تم التحقق",
          "Search": "يبحث",
          "Start typing to search": "ابدأ في الكتابة للبحث",
          "Code": "شفرة",
          "Phone": "هاتف",
          "Salon Name": "اسم الصالون",
          "Confirm Password": "تأكيد كلمة المرور",
          "Fee Started Price": "بدأت الرسوم السعر",
          "Select Category": "اختر الفئة",
          "Address": "تبوك",
          "Zipcode": "الرمز البريدي",
          "Select Latitude & Longitude from here :":
              "حدد خط العرض والعرض من هنا:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.":
              "الرجاء إدخال خط العرض والطول الصالح وإلا قد لا يعمل التطبيق بشكل صحيح.",
          "Your Latitude": "خط العرض الخاص بك",
          "Your Longitude": "خط الطول",
          "No Internet Connection": "لا يوجد اتصال إنترنت",
          "Developed By ": "طورت بواسطة",
          "Select Stylist": "حدد المصمم",
          "Appoinment": "ميعاد",
          "Profile": "الملف الشخصي",
          "Forgot Password ?": "هل نسيت كلمة السر ؟",
          "Send OTP": "إرسال OTP",
          "Gereate Password": "كلمة مرور gereate",
          "New Password": "كلمة السر الجديدة",
          "Update Password": "تطوير كلمة السر",
          "All fields are required!": "جميع الحقول مطلوبة!",
          "Please select specialist": "الرجاء تحديد أخصائي",
          "Please wait": "أرجو الإنتظار",
          "Save Packages": "حفظ الحزم",
          "packages update !": "تحديث الحزم!",
          "Discount must be less than 100": "يجب أن يكون الخصم أقل من 100",
          "Services Added !": "وأضاف الخدمات!",
          "services update !": "تحديث الخدمات!",
          "Please select time": "الرجاء تحديد الوقت",
          "Already exist": "موجود مسبقا",
          "Slots are empty": "الفتحات فارغة",
          "Save Specialist": "حفظ أخصائي",
          "Already added": "تم الاضافة مسبقا",
          "January": "يناير",
          "February": "شهر فبراير",
          "March": "يمشي",
          "April": "أبريل",
          "May": "مايو",
          "June": "يونيه",
          "July": "يوليو",
          "August": "أغسطس",
          "September": "سبتمبر",
          "October": "اكتوبر",
          "November": "شهر نوفمبر",
          "December": "ديسمبر",
          "Created": "مخلوق",
          "Accepted": "وافقت",
          "Rejected": "مرفوض",
          "Ongoing": "جاري التنفيذ",
          "Completed": "مكتمل",
          "Cancelled": "ألغيت",
          "Refunded": "استرداد",
          "Delayed": "تأخير",
          "Panding Payment": "دفع الدفعة",
          "New message received": "استلمت رسالة جديدة",
          "Select Your Cities !": "حدد مدنك!",
          "City Updated": "تحديث المدينة",
          "All fields are required": "جميع الحقول مطلوبة",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "New Mail Request Received": "تم استلام طلب البريد الجديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل الاتصال الجديدة",
          "We have received your request, we will respond on your issue soon":
              "لقد تلقينا طلبك ، وسوف نرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Contact Information Sent": "معلومات الاتصال المرسلة",
          "Okay": "تمام",
          "Please select category": "الرجاء تحديد الفئة",
          "Save Products": "حفظ المنتجات",
          "Gallery Updated": "معرض تحديث",
          "Please select one of the categories": "الرجاء تحديد واحدة من الفئات",
          "Categories Updated": "فئات تحديث",
          "Update Salon": "تحديث صالون",
          "Access denied": "تم الرفض",
          "Something went wrong": "هناك خطأ ما",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Something went wrong while signup": "حدث خطأ ما أثناء الاشتراك",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "COD": "سمك القد",
          "Stripe": "شريط",
          "PayPal": "PayPal",
          "Paytm": "paytm",
          "Razorpay": "رازورباي",
          "Instamojo": "Instamojo",
          "Paystack": "PayStack",
          "Flutterwave": "Flutterwave",
          "Cancelled by user": "ألغى المستخدم",
          "Status Updated": "تم تحديث الحالة",
          "New Notificaiton": "NEWIFICAITON الجديد",
          "Your Appointment status is Changed": "تم تغيير حالة موعدك",
          "Choose": "يختار",
          "Complaints": "شكاوي",
          "Chat": "دردشة",
          "Call": "مكالمة",
          "item remove successfully": "العنصر إزالة بنجاح",
          "Updated": "محدث",
          "Your order status is Changed": "تم تغيير حالة طلبك",
          "Select Service": "حدد الخدمة",
          "Products Categories": "فئات المنتجات",
          "Your Email is Verified": "تم التحقق من بريدك الإلكتروني",
          "Phone number is required": "رقم الهاتف مطلوب",
          "Please verify email": "يرجى التحقق من البريد الإلكتروني",
          "Please verify phone number": "يرجى التحقق من رقم الهاتف",
          "Please upload your cover photo": "يرجى تحميل صورة الغلاف الخاصة بك",
          "password does not match": "كلمة السر غير متطابقة",
          "Success!": "النجاح!",
          "Your Request is submitted": "تم تقديم طلبك",
          "Slot Remove Successfully": "فتحة إزالة بنجاح",
          "All Fields Are Required": "جميع الحقول مطلوبة",
          "Password mismatch": "عدم تطابق كلمة المرور",
          "Password Updated": "تم تحديث كلمة السر"
        },
      };
}
